#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Jesse Rubin
"""
Even Fibonacci numbers
Problem 2 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

#finnn

import helpme as hm

# first_10 = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

almost_first_10 = hm.fib(10)

# print(almost_first_10)

l = sum([pood for pood in [hm.fib(i) for i in range(50)] if pood%2==0 and pood<=4000000])
print("sum: {}".format(l))