# -*- coding: utf-8 -*-
# Jesse Rubin - project Euler
"""
Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So
the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1, 3
 6: 1, 2, 3, 6
10: 1, 2, 5, 10
15: 1, 3, 5, 15
21: 1, 3, 7, 21
28: 1, 2, 4, 7, 14, 28

We can see that 28 is the first triangle number to have over five divisors_gen.

What is the value of the first triangle number to have over five hundred
divisors_gen?
"""

from pupy.maths import divisors_gen


def p012():
    cur_tri = 1
    maxmax = 1
    i = 1
    while maxmax < 500:
        i += 1
        cur_tri += i
        numDivs = sum(1 for _ in divisors_gen(cur_tri))
        if numDivs > maxmax:
            maxmax = numDivs
    return cur_tri


if __name__ == '__main__':
    answer = p012()
    print('triangle #: {}'.format(answer))  # cur #: 76576500

